"use strict"

var set2 = [
{name:"arrow-left-bold",tag:"o-none"},
{name:"arrow-right",tag:"o-none"},
{name:"arrow-right-bold",tag:"o-none"},
{name:"bottle-baby",tag:"o-none"},
{name:"bubble-dialog-rainbow",tag:"o-none"},
{name:"car-collection",tag:"o-none"},
{name:"car-construction",tag:"o-none"},
{name:"car-sheep-left",tag:"o-none"},
{name:"car-sheep-left-boy",tag:"o-none"},
{name:"cat-fitness",tag:"o-none"},
{name:"cat-joga-up",tag:"o-none"},
{name:"cat-jump-balkony",tag:"o-none"},
{name:"cat-jump-right",tag:"o-none"},
{name:"cat-look-ne",tag:"o-none"},
{name:"coffee-machine-beans",tag:"o-none"},
{name:"dialog-users",tag:"o-none"},
{name:"doctor-ambulance-car",tag:"o-none"},
{name:"dog-haski-cooking",tag:"o-none"},
{name:"eyes-right",tag:"o-none"},
{name:"fence",tag:"o-none"},
{name:"film-movie",tag:"o-none"},
{name:"fire-camp",tag:"o-none"},
{name:"fire-matches",tag:"o-none"},
{name:"girl-luanda-by-ennoia",tag:"o-none"},
{name:"hide-box",tag:"o-none"},
{name:"loading-cat",tag:"o-none"},
{name:"log-saw",tag:"o-none"},
{name:"menu-text",tag:"o-none"},
{name:"picture-corners",tag:"o-none"},
{name:"picture-wall-horizontal",tag:"o-none"},
{name:"picture-wall-vertical",tag:"o-none"},
{name:"piggy-a",tag:"o-none"},
{name:"piggy-b",tag:"o-none"},
{name:"piggy-c",tag:"o-none"},
{name:"piggy-d",tag:"o-none"},
{name:"piggy-e",tag:"o-none"},
{name:"pot-poo",tag:"o-none"},
{name:"robot",tag:"o-none"},
{name:"robot-boy",tag:"o-none"},
{name:"room-doors",tag:"o-none"},
{name:"room-kitchen",tag:"o-none"},
{name:"science-chemical-liquid",tag:"o-none"},
{name:"sheep-loading",tag:"o-none"},
{name:"sheep-pank-empty",tag:"o-none"},
{name:"sheep-pank-full",tag:"o-none"},
{name:"shipping-sheep-truck",tag:"o-none"},
{name:"stats-meeter",tag:"o-none"},
{name:"support-phone",tag:"o-none"},
{name:"symbol-hexagon-bolt",tag:"o-none"},
{name:"symbol-square-stop",tag:"o-none"},
{name:"symbol-triangle-play",tag:"o-none"},
{name:"symbol-wc",tag:"o-none"},
{name:"user-a",tag:"o-none"},
{name:"user-b",tag:"o-none"},
{name:"users-group",tag:"o-none"},
{name:"users-group-collection",tag:"o-none"},
{name:"witch",tag:"o-none"},
{name:"arrow-grow-ne",tag:"o-none"},
{name:"arrow-left",tag:"o-none"}
];

// o o o o o o o o o o

var dataIcons = [

{name:"cat-chaoss",tag:"o-chars o-home"},
{name:"cat-sleep",tag:"o-chars o-home"},
{name:"chair",tag:"o-obj"},
{name:"cloud",tag:"o-obj"},
{name:"cloud-a",tag:"o-obj"},
{name:"cloud-lighting",tag:"o-obj"},
{name:"coffee",tag:"o-obj"},
{name:"coffee-and-milk",tag:"o-obj o-home"},
{name:"compass",tag:"o-ui"},
{name:"computer-connection",tag:"o-ui"},
{name:"computer-signal",tag:"o-ui"},
{name:"cooperation-water-worms",tag:"o-chars"},
{name:"draw-sheep-street",tag:"o-sheep o-chars o-home"},
{name:"exit-man",tag:"o-chars o-home"},
{name:"flowers",tag:"o-obj"},
{name:"fly-right",tag:"o-chars"},
{name:"fox-important",tag:"o-chars"},
{name:"geometry",tag:"o-ui o-home"},
{name:"girl-bell",tag:"o-chars o-home"},
{name:"girl-dance",tag:"o-chars"},
{name:"girl-dog",tag:"o-chars o-home"},
{name:"home-with-dog",tag:"o-obj"},
{name:"justice",tag:"o-chars"},
{name:"lauki-sheep-tech",tag:"o-sheep"},
{name:"mouse-rain",tag:"o-chars o-home"},
{name:"music-guitar",tag:"o-obj"},
{name:"musiciant-street",tag:"o-chars"},
{name:"music-speakers",tag:"o-obj"},
{name:"officeboard",tag:"o-ui o-home"},
{name:"papers",tag:"o-ui"},
{name:"pen",tag:"o-ui o-chars"},
{name:"pencil-menium",tag:"o-ui o-chars"},
{name:"pencil-square-mini",tag:"o-ui o-chars"},
{name:"pinguin-duel",tag:"o-chars"},
{name:"plane-paper",tag:"o-obj"},
{name:"poker-game",tag:"o-chars"},
{name:"postamp",tag:"o-ui"},
{name:"products",tag:"o-ui"},
{name:"products-more",tag:"o-ui o-home"},
{name:"profile-double-sheep",tag:"o-sheep o-ui o-home"},
{name:"profile-sheep",tag:"o-sheep o-ui"},
{name:"projector",tag:"o-ui"},
{name:"safety-sheep",tag:"o-sheep"},
{name:"scissors",tag:"o-ui"},
{name:"service-sheep",tag:"o-sheep"},
{name:"shape-height",tag:"o-ui"},
{name:"shape-roll",tag:"o-ui"},
{name:"shape-width",tag:"o-ui"},
{name:"sheep-3x3",tag:"o-sheep o-ui"},
{name:"sheep-atom",tag:"o-sheep"},
{name:"sheep-flowers",tag:"o-sheep"},
{name:"sheep-help",tag:"o-sheep o-ui o-home"},
{name:"sheep-lasvegas",tag:"o-sheep"},
{name:"sheep-princess-feelings",tag:"o-sheep"},
{name:"sheep-pushkin",tag:"o-sheep"},
{name:"sheep-right-look",tag:"o-sheep"},
{name:"sheep-round-nw",tag:"o-sheep"},
{name:"sheep-round-roll",tag:"o-sheep"},
{name:"sheep-round-se",tag:"o-sheep o-home"},
{name:"sheep-round-w",tag:"o-sheep"},
{name:"sheep-travel-dog",tag:"o-sheep"},
{name:"sheet-landscape",tag:"o-ui"},
{name:"ship-cat-stars",tag:"o-chars"},
{name:"smartphone-signal",tag:"o-ui"},
{name:"smile-happy-girl",tag:"o-ui o-home"},
{name:"smile-sad-gril",tag:"o-ui o-home"},
{name:"snowman",tag:"o-chars"},
{name:"spinner-worms",tag:"o-ui"},
{name:"squirrel-computer",tag:"o-ui"},
{name:"stats-bars",tag:"o-ui"},
{name:"stats-worms",tag:"o-ui o-home"},
{name:"symbol-dollar",tag:"o-ui"},
{name:"symbol-injan",tag:"o-ui"},
{name:"symbol-no",tag:"o-ui"},
{name:"symbol-pentagram-sheep",tag:"o-ui"},
{name:"symbol-yes",tag:"o-ui"},
{name:"users",tag:"o-ui"},
{name:"wine",tag:"o-obj o-home"},
{name:"writing",tag:"o-ui"},
{name:"anchor",tag:"o-ui"},
{name:"bird-warrior-left",tag:"o-ui"},
{name:"bird-warrior-right",tag:"o-ui"},
{name:"boat-sheep",tag:"o-sheep"},
{name:"book-open",tag:"o-ui"},
{name:"book-open-worms",tag:"o-ui o-home"},
{name:"boom-nw",tag:"o-ui"},
{name:"boy",tag:"o-chars"},
{name:"bugfix-crab-buben",tag:"o-ui o-home"},
{name:"car-sheep-red",tag:"o-sheep o-home"},
{name:"castle",tag:"o-obj o-home"}
];
var dataIconsMd = {
  path: 'icons/'
}
var dataIcons = dataIcons.concat(set2);

// o o o o o o o o o o

var appData = 
{
  pageIsLoaded: false,
  isSet: true
}

// o o o o o o o o o o